-- ══════════════════════════════════════════════
--  OTOTECH ONLINE QUESTIONS MANAGEMENT SYSTEM — SUPABASE SETUP SQL
--  Run this in: Supabase → SQL Editor → New Query
--  300 questions: 50 per category × 6 categories
-- ══════════════════════════════════════════════

-- 1. QUESTIONS TABLE
CREATE TABLE IF NOT EXISTS questions (
  id              SERIAL PRIMARY KEY,
  question        TEXT NOT NULL,
  category        TEXT NOT NULL CHECK (category IN ('civil', 'affairs', 'edu', 'ict', 'religion', 'entrance')),
  option_a        TEXT NOT NULL,
  option_b        TEXT NOT NULL,
  option_c        TEXT NOT NULL,
  option_d        TEXT NOT NULL,
  correct_answer  INTEGER NOT NULL CHECK (correct_answer IN (0, 1, 2, 3)),
  active          BOOLEAN DEFAULT TRUE,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- 2. EXAM RESULTS TABLE
CREATE TABLE IF NOT EXISTS exam_results (
  id                SERIAL PRIMARY KEY,
  name              TEXT NOT NULL,
  email             TEXT,
  phone             TEXT,
  organisation      TEXT,
  selected_category TEXT,
  score             INTEGER NOT NULL,
  total             INTEGER NOT NULL,
  percentage        INTEGER NOT NULL,
  grade             TEXT NOT NULL,
  correct_count     INTEGER DEFAULT 0,
  wrong_count       INTEGER DEFAULT 0,
  skipped_count     INTEGER DEFAULT 0,
  civil_score       INTEGER DEFAULT 0,
  affairs_score     INTEGER DEFAULT 0,
  edu_score         INTEGER DEFAULT 0,
  ict_score         INTEGER DEFAULT 0,
  religion_score    INTEGER DEFAULT 0,
  entrance_score    INTEGER DEFAULT 0,
  answers_detail    JSONB,
  time_taken_secs   INTEGER,
  taken_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ACCESS CODES TABLE
CREATE TABLE IF NOT EXISTS access_codes (
  id          SERIAL PRIMARY KEY,
  code        TEXT NOT NULL UNIQUE,
  label       TEXT,
  category    TEXT CHECK (category IN ('civil', 'affairs', 'edu', 'ict', 'religion', 'entrance')),
  active      BOOLEAN DEFAULT TRUE,
  use_count   INTEGER DEFAULT 0,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ENABLE REALTIME on exam_results
ALTER TABLE exam_results REPLICA IDENTITY FULL;

-- 5. ROW LEVEL SECURITY
ALTER TABLE questions     ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_results  ENABLE ROW LEVEL SECURITY;
ALTER TABLE access_codes  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read questions"  ON questions    FOR SELECT USING (true);
CREATE POLICY "Public read codes"      ON access_codes FOR SELECT USING (true);
CREATE POLICY "Public insert results"  ON exam_results FOR INSERT WITH CHECK (true);
CREATE POLICY "Public read results"    ON exam_results FOR SELECT USING (true);
CREATE POLICY "Admin manage questions" ON questions    FOR ALL USING (true);
CREATE POLICY "Admin manage codes"     ON access_codes FOR ALL USING (true);

-- 6. SEED CATEGORY-SPECIFIC ACCESS CODES (one per category)
INSERT INTO access_codes (code, label, category, active) VALUES
  ('CIVIL2025',    'Civil Service Rules Exam',  'civil',    true),
  ('AFFAIRS2025',  'Current Affairs Exam',       'affairs',  true),
  ('EDU2025',      'Education Exam',             'edu',      true),
  ('ICT2025',      'ICT Exam',                   'ict',      true),
  ('RELIGION2025', 'Religion Exam',              'religion', true),
  ('ENTRANCE2025', 'Common Entrance Exam',       'entrance', true)
ON CONFLICT (code) DO NOTHING;

-- ══════════════════════════════════════════════
-- 7. SEED ALL 300 QUESTIONS (50 per category)
-- ══════════════════════════════════════════════
INSERT INTO questions (question, category, option_a, option_b, option_c, option_d, correct_answer) VALUES

-- ── CIVIL SERVICE RULES (50) ──
('Under the Nigerian Civil Service Rules, what is the minimum notice period for resignation of a confirmed officer?', 'civil', 'One month', 'Three months', 'Two months', 'Six months', 0),
('Which body is primarily responsible for the appointment, promotion, and discipline of Federal civil servants in Nigeria?', 'civil', 'Federal Executive Council', 'Federal Civil Service Commission', 'Office of the Head of Service', 'National Council of State', 1),
('According to Civil Service Rules, an officer on suspension shall receive what fraction of his salary?', 'civil', 'Full salary', 'Three-quarters salary', 'Half salary', 'No salary', 2),
('What is the maximum number of days allowed for casual leave per year under Nigerian Civil Service Rules?', 'civil', '7 days', '10 days', '14 days', '21 days', 0),
('In the Nigerian civil service, the Scheme of Service is primarily designed to:', 'civil', 'Determine salaries of officers', 'Define entry qualifications and career progression', 'Outline disciplinary procedures', 'Set annual targets for MDAs', 1),
('A civil servant found guilty of gross misconduct can be subjected to:', 'civil', 'Only demotion', 'Only fine', 'Dismissal without benefits', 'Transfer to another ministry', 2),
('What document governs the financial dealings of Nigerian federal civil servants?', 'civil', 'Finance Act', 'Financial Regulations', 'Annual Appropriation Act', 'Public Procurement Act', 1),
('A civil servant''s annual leave entitlement after 10 years of service is:', 'civil', '21 days', '30 days', '28 days', '35 days', 1),
('Which of the following is punishable as serious misconduct?', 'civil', 'Arriving 10 minutes late once', 'Engaging in partisan political activities', 'Wearing informal clothing', 'Missing a single meeting', 1),
('The probationary period for a newly appointed officer in the Nigerian civil service is:', 'civil', '6 months', '1 year', '2 years', '3 years', 2),
('Sick leave with full pay for a confirmed officer can be granted for a maximum of:', 'civil', '3 months', '6 months', '1 year', '2 years', 1),
('IPPIS was introduced primarily to:', 'civil', 'Monitor civil servant performance', 'Eliminate ghost workers from the payroll', 'Automate promotion exercises', 'Manage pension fund investments', 1),
('Maternity leave for female civil servants in Nigeria is:', 'civil', '6 weeks', '8 weeks', '12 weeks', '3 months', 2),
('Under the Pension Reform Act, the mandatory contribution rate for civil servants is:', 'civil', 'Employee 7.5%, Employer 7.5%', 'Employee 5%, Employer 10%', 'Employee 10%, Employer 5%', 'Employee 8%, Employer 12%', 0),
('In the Nigerian civil service, Grade Level 16 and above are classified as:', 'civil', 'Junior staff', 'Middle management', 'Senior management', 'Directors and above', 2),
('The Head of the Civil Service of the Federation holds which rank?', 'civil', 'Grade Level 16', 'Equivalent of Permanent Secretary', 'Minister', 'Above Permanent Secretary', 3),
('Under which Chapter of Civil Service Rules are conduct and discipline provisions covered?', 'civil', 'Chapter 1', 'Chapter 4', 'Chapter 10', 'Chapter 16', 1),
('An officer wishing to undertake outside employment must obtain approval from:', 'civil', 'The Ministry of Finance', 'His immediate supervisor', 'The appropriate Commission', 'The Inspector General', 2),
('A "Schedule Officer" in the Nigerian civil service is:', 'civil', 'An officer who manages schedules', 'An accounting officer responsible for expenditure control', 'An officer due for promotion', 'An officer listed for transfer', 1),
('The "Estacade" in the Nigerian civil service context refers to:', 'civil', 'A type of office accommodation', 'A daily subsistence allowance for officers on tour', 'A financial regulatory body', 'A grade level classification', 1),
('Which of the following is NOT a legitimate reason for dismissal of a civil servant?', 'civil', 'Theft of public funds', 'Conviction of a criminal offence', 'Failing a promotion exam once', 'Gross misconduct', 2),
('The Federal Civil Service Commission was established under which section of the 1999 Constitution?', 'civil', 'Section 153', 'Section 197', 'Section 208', 'Section 174', 0),
('What is the minimum qualification for appointment into the civil service at Grade Level 07?', 'civil', 'WAEC certificate', 'OND/NCE', 'HND/B.Sc degree', 'Postgraduate degree', 2),
('Paternity leave for male civil servants in Nigeria is:', 'civil', '3 days', '5 days', '7 days', '14 days', 1),
('Which of the following describes "secondment" in the civil service?', 'civil', 'Transfer of an officer to another ministry permanently', 'Temporary transfer to another organisation while retaining substantive post', 'Demotion to a lower grade', 'Promotion to a higher grade', 1),
('The official working hours in the Nigerian civil service are:', 'civil', '7am – 3pm', '8am – 4pm', '8am – 5pm', '9am – 5pm', 1),
('What happens to a civil servant who is absent from duty without leave for more than 14 days?', 'civil', 'They are warned', 'They are fined', 'They are deemed to have vacated their post', 'They are transferred', 2),
('Which grade level is the entry point for a direct recruit with a first degree in the Nigerian civil service?', 'civil', 'Grade Level 06', 'Grade Level 07', 'Grade Level 08', 'Grade Level 09', 2),
('An "Acting" appointment in the civil service means:', 'civil', 'A permanent appointment to a higher post', 'A temporary appointment to a higher post pending substantive filling', 'A lateral transfer', 'A contract appointment', 1),
('The body that handles discipline of officers in the police force equivalent to FCSC is:', 'civil', 'ICPC', 'PSC (Police Service Commission)', 'National Security Council', 'EFCC', 1),
('Study leave with pay in the Nigerian civil service is granted for a maximum of:', 'civil', '1 year', '2 years', '3 years', '4 years', 2),
('Which of these is NOT one of the core values of the Nigerian civil service?', 'civil', 'Integrity', 'Accountability', 'Profitability', 'Loyalty', 2),
('The annual performance evaluation report for civil servants is called:', 'civil', 'Staff Appraisal Form', 'Annual Confidential Report (ACR)', 'Performance Review Sheet', 'Staff Assessment Record', 1),
('An officer who is compulsorily retired is entitled to:', 'civil', 'Full pension benefits', 'Reduced pension benefits', 'No pension at all', 'Only gratuity', 0),
('Which circular governs the conduct of civil servants on social media in Nigeria?', 'civil', 'OHCSF Circular No. 01/2020', 'OHCSF Social Media Policy 2019', 'FMF Circular 2018', 'FCSC Directive 2021', 1),
('What is the correct procedure for a civil servant who wishes to contest an election?', 'civil', 'Apply for study leave', 'Resign from the civil service before contesting', 'Apply for annual leave', 'Get permission from the Permanent Secretary', 1),
('The principle of "due process" in the civil service means:', 'civil', 'Following all laid down rules and procedures before any action', 'Paying all dues promptly', 'Processing files quickly', 'Approving requests without delay', 0),
('Which of the following is an example of financial misconduct in the civil service?', 'civil', 'Taking annual leave', 'Submitting a wrong timesheet', 'Falsifying payment vouchers', 'Missing a departmental meeting', 2),
('Government "subvention" to a parastatal refers to:', 'civil', 'A loan from the government', 'An annual grant from government to fund operations', 'A tax collected by the parastatal', 'A penalty imposed on the parastatal', 1),
('What does "Gazette" mean in the Nigerian civil service context?', 'civil', 'An internal memo', 'The official government publication of laws, appointments and notices', 'A financial report', 'A staff newsletter', 1),
('An officer on interdiction pending investigation receives:', 'civil', 'Full salary', 'Half salary', 'No salary', 'Allowances only', 1),
('The Public Service Rules (PSR) in Nigeria were most recently revised in:', 'civil', '1999', '2008', '2011', '2021', 1),
('What is the difference between a "ministry" and a "department" in the Nigerian civil service?', 'civil', 'There is no difference', 'A ministry is headed by a minister while a department is a subdivision under a ministry', 'A department is bigger than a ministry', 'A ministry handles only federal matters', 1),
('A civil servant''s entitlement to pension vests after a minimum of:', 'civil', '5 years of service', '10 years of service', '15 years of service', '20 years of service', 1),
('Which of the following best describes "due process" in procurement?', 'civil', 'Buying the cheapest goods', 'Following the Bureau of Public Procurement Act guidelines', 'Approving expenditure quickly', 'Buying from preferred vendors', 1),
('The Servicom initiative in Nigeria was designed to:', 'civil', 'Fight corruption in government', 'Ensure quality service delivery to citizens', 'Manage government payroll', 'Provide loans to civil servants', 1),
('Which body was established to fight corruption in the Nigerian civil service?', 'civil', 'EFCC', 'ICPC', 'DSS', 'NBS', 1),
('What is the retirement age for civil servants in Nigeria?', 'civil', '55 years or 30 years of service', '60 years or 35 years of service', '65 years or 35 years of service', '60 years or 40 years of service', 1),
('The "Treasury Single Account" (TSA) policy in Nigeria was fully implemented in:', 'civil', '2011', '2013', '2015', '2017', 2),
('An "Accounting Officer" in the Nigerian civil service is typically the:', 'civil', 'Minister', 'Permanent Secretary', 'Director of Finance', 'Accountant General', 1),

-- ── CURRENT AFFAIRS (50) ──
('Who is the current President of Nigeria as of 2024–2025?', 'affairs', 'Muhammadu Buhari', 'Peter Obi', 'Bola Ahmed Tinubu', 'Atiku Abubakar', 2),
('In 2023, Nigeria removed the subsidy on which commodity?', 'affairs', 'Electricity', 'Petrol (fuel subsidy)', 'Cooking gas', 'Kerosene', 1),
('The EFCC Chairman as of 2024 is:', 'affairs', 'Ibrahim Magu', 'Abdulrasheed Bawa', 'Ola Olukoyede', 'Nuhu Ribadu', 2),
('Nigeria''s 2024 national budget was titled:', 'affairs', 'Budget of Consolidation', 'Budget of Renewed Hope', 'Budget of Renewal', 'Budget of Economic Restoration', 1),
('The CBN Governor appointed in 2023 is:', 'affairs', 'Godwin Emefiele', 'Yemi Cardoso', 'Kingsley Moghalu', 'Lamido Sanusi', 1),
('Nigeria officially joined the AfCFTA as a full member in:', 'affairs', '2019', '2021', '2023', '2024', 2),
('The "Renewed Hope Agenda" is associated with:', 'affairs', 'National Assembly', 'The Presidency under Bola Tinubu', 'The Judiciary', 'Federal Ministry of Finance', 1),
('Which country hosted the 2023 AFCON?', 'affairs', 'Nigeria', 'South Africa', 'Ivory Coast', 'Ghana', 2),
('Nigeria''s Naira exchange rate unification in 2023 was championed by:', 'affairs', 'The National Assembly', 'The CBN under new leadership', 'The Federal Ministry of Finance', 'The World Bank mission', 1),
('Which Nigerian state was created most recently (36th state)?', 'affairs', 'Zamfara', 'Ebonyi', 'Ekiti', 'Gombe', 2),
('Who won the 2023 AFCON Golden Boot award?', 'affairs', 'Victor Osimhen', 'Emilio Nsue', 'Sebastien Haller', 'Achraf Hakimi', 1),
('The National Population Commission (NPC) conducted Nigeria''s national census in:', 'affairs', '2019', '2021', '2023', '2024', 2),
('Nigeria''s Vice President as of 2024 is:', 'affairs', 'Yemi Osinbajo', 'Kashim Shettima', 'Peter Obi', 'Atiku Abubakar', 1),
('Which Nigerian won the Nobel Prize in Literature in 1986?', 'affairs', 'Chinua Achebe', 'Wole Soyinka', 'Ben Okri', 'Chimamanda Adichie', 1),
('The "Naira Redesign" policy in Nigeria was introduced in:', 'affairs', '2021', '2022', '2023', '2024', 1),
('ECOWAS headquarters is located in:', 'affairs', 'Dakar', 'Accra', 'Lagos', 'Abuja', 2),
('Which country did Nigeria defeat in the 2023 AFCON semi-finals?', 'affairs', 'Angola', 'Cameroon', 'South Africa', 'Ghana', 2),
('What was the name of Nigeria''s 2023 general election system used by INEC?', 'affairs', 'SMART voting', 'BIVAS (Bimodal Voter Accreditation System)', 'Electronic Voting Machine', 'Direct Polling System', 1),
('Who was declared winner of Nigeria''s 2023 presidential election?', 'affairs', 'Atiku Abubakar', 'Peter Obi', 'Bola Ahmed Tinubu', 'Rabiu Kwankwaso', 2),
('The National Security Adviser (NSA) to President Tinubu as of 2024 is:', 'affairs', 'Babagana Monguno', 'Nuhu Ribadu', 'Zakari Usman', 'Mohammed Badaru', 1),
('Which Nigerian city hosted the 2024 ECOWAS Summit?', 'affairs', 'Lagos', 'Kano', 'Abuja', 'Ibadan', 2),
('Nigeria''s Senate President as of 2024 is:', 'affairs', 'Ahmad Lawan', 'Godswill Akpabio', 'Bukola Saraki', 'David Mark', 1),
('The Nigerian Electricity Regulatory Commission (NERC) oversees:', 'affairs', 'Oil and gas regulation', 'Power sector regulation', 'Telecommunications regulation', 'Water supply regulation', 1),
('Which Nigerian state has the highest population according to recent estimates?', 'affairs', 'Lagos', 'Kano', 'Rivers', 'Oyo', 0),
('The "Student Loan Act" was signed into law in Nigeria in:', 'affairs', '2022', '2023', '2024', '2025', 1),
('Who is the current Chairman of INEC as of 2024?', 'affairs', 'Attahiru Jega', 'Mahmood Yakubu', 'Amina Zakari', 'Charles Soludo', 1),
('Nigeria became a member of OPEC in which year?', 'affairs', '1960', '1965', '1971', '1975', 2),
('The Nigerian National Petroleum Company Limited (NNPCL) replaced NNPC in:', 'affairs', '2019', '2021', '2022', '2023', 2),
('Which country is Nigeria''s largest trading partner?', 'affairs', 'USA', 'China', 'UK', 'India', 1),
('Nigeria''s Speaker of the House of Representatives as of 2024 is:', 'affairs', 'Femi Gbajabiamila', 'Tajudeen Abbas', 'Yakubu Dogara', 'Dimeji Bankole', 1),
('The Dangote Refinery is located in which state?', 'affairs', 'Delta', 'Ogun', 'Lagos', 'Rivers', 2),
('Nigeria''s Minister of Finance as of 2024 is:', 'affairs', 'Zainab Ahmed', 'Wale Edun', 'Kemi Adeosun', 'Ngozi Okonjo-Iweala', 1),
('Which country won the 2022 FIFA World Cup?', 'affairs', 'France', 'Brazil', 'Argentina', 'Germany', 2),
('The African Development Bank (AfDB) headquarters is in:', 'affairs', 'Nairobi', 'Lagos', 'Abidjan', 'Accra', 2),
('Nigeria''s current Chief Justice as of 2024 is:', 'affairs', 'Kayode Ariwoola', 'Tanko Muhammad', 'Ibrahim Tanko Muhammad', 'Olukayode Ariwoola', 0),
('The CAADP was launched by:', 'affairs', 'UN', 'World Bank', 'African Union', 'ECOWAS', 2),
('The 2023 coup in Niger Republic ousted which president?', 'affairs', 'Mahamadou Issoufou', 'Mohamed Bazoum', 'Mahamane Ousmane', 'Ali Saibou', 1),
('Nigeria''s first satellite (NigeriaSat-1) was launched in:', 'affairs', '2000', '2003', '2005', '2008', 1),
('Which is the newest addition to the UN Security Council permanent members?', 'affairs', 'Germany', 'Japan', 'India', 'None — P5 unchanged', 3),
('The International Criminal Court (ICC) is headquartered in:', 'affairs', 'Geneva', 'New York', 'The Hague', 'Brussels', 2),
('Which Nigerian bank is the largest by total assets as of 2024?', 'affairs', 'GTBank', 'Zenith Bank', 'Access Bank', 'First Bank', 2),
('The National Agency for the Prohibition of Trafficking in Persons (NAPTIP) is headed as of 2024 by:', 'affairs', 'Julie Okah-Donli', 'Fatima Waziri-Azi', 'Arinze Orakwe', 'Binta Bello', 1),
('Nigeria''s current Inspector General of Police as of 2024 is:', 'affairs', 'Usman Alkali Baba', 'Ibrahim Idris', 'Kayode Egbetokun', 'Mohammed Adamu', 2),
('Which country hosted the 2023 G20 Summit?', 'affairs', 'Indonesia', 'Japan', 'India', 'South Africa', 2),
('Nigeria was suspended from the Commonwealth of Nations in:', 'affairs', '1993', '1995', '1999', '2001', 1),
('The Petroleum Industry Act (PIA) was signed into law in Nigeria in:', 'affairs', '2019', '2021', '2022', '2023', 1),
('Nigeria''s current Minister of Education as of 2024 is:', 'affairs', 'Adamu Adamu', 'Tahir Mamman', 'Sam Egwu', 'Ibrahim Shekarau', 1),
('The New Development Bank (NDB) was established by which group of nations?', 'affairs', 'G7', 'G20', 'BRICS', 'ASEAN', 2),
('Nigeria''s 2025 national budget size was approximately:', 'affairs', '15 trillion Naira', '25 trillion Naira', '35 trillion Naira', '45 trillion Naira', 2),
('The African Continental Free Trade Area (AfCFTA) secretariat is located in:', 'affairs', 'Addis Ababa', 'Accra', 'Nairobi', 'Lagos', 1),

-- ── EDUCATION (50) ──
('The body responsible for regulating basic and secondary education standards in Nigeria is:', 'edu', 'NUC', 'NBTE', 'NERDC', 'WAEC', 2),
('The UBE Act provides for how many years of free and compulsory education?', 'edu', '6 years', '8 years', '9 years', '10 years', 2),
('JAMB was established primarily to:', 'edu', 'Conduct WAEC examinations', 'Regulate university academic standards', 'Conduct unified admissions into tertiary institutions', 'Manage student bursaries', 2),
('The 6-3-3-4 system of education in Nigeria means:', 'edu', '6 primary, 3 JSS, 3 SSS, 4 university', '6 primary, 3 middle, 3 technical, 4 college', '6 nursery, 3 primary, 3 junior, 4 secondary', '6 primary, 3 JSS, 3 technical, 4 polytechnic', 0),
('The National Policy on Education in Nigeria was first published in:', 'edu', '1965', '1977', '1985', '1993', 1),
('Which body conducts the National Common Entrance Examination for JSS1 admission?', 'edu', 'WAEC', 'JAMB', 'NECO', 'NERDC', 2),
('NUC is empowered to do all of the following EXCEPT:', 'edu', 'Grant university licences', 'Set minimum academic standards', 'Conduct JAMB UTME', 'Accredit academic programmes', 2),
('Under the Child''s Right Act, the minimum working age is:', 'edu', '12 years', '15 years', '16 years', '18 years', 1),
('TRCN was established to:', 'edu', 'Train teachers at federal colleges', 'Regulate and control the teaching profession', 'Set WAEC marking schemes', 'Manage UBEC funds', 1),
('UBEC disburses matching grants to states on what basis?', 'edu', 'Population of school-age children only', 'States must provide counterpart funding', 'Annual federal allocation automatically', 'Request from state governors only', 1),
('The National Examinations Council (NECO) was established in:', 'edu', '1993', '1999', '2001', '2004', 1),
('WAEC was founded in:', 'edu', '1948', '1952', '1956', '1960', 0),
('The West African Senior School Certificate (WASSC) is issued by:', 'edu', 'NECO', 'JAMB', 'WAEC', 'NUC', 2),
('The minimum number of credits required to gain university admission in Nigeria is:', 'edu', '3 credits', '5 credits', '4 credits', '6 credits', 1),
('Which Federal Government policy provides free education at the primary level in Nigeria?', 'edu', 'UBEC Act', 'FGN Free Education Policy', 'UPE Decree', 'Education for All Act', 0),
('The National Board for Technical Education (NBTE) accredits:', 'edu', 'Universities', 'Polytechnics and technical colleges', 'Secondary schools', 'Primary schools', 1),
('Federal Government Colleges in Nigeria are administered by:', 'edu', 'State governments', 'The Federal Ministry of Education', 'NUC', 'WAEC', 1),
('The NYSC scheme was established in:', 'edu', '1967', '1970', '1973', '1976', 2),
('How many years is a standard bachelor''s degree programme in Nigeria?', 'edu', '3 years', '4 years', '4 to 5 years depending on course', '6 years', 2),
('NAPPS stands for:', 'edu', 'National Association of Primary and Post-primary Schools', 'National Association of Proprietors of Private Schools', 'National Agency for Primary and Polytechnic Schools', 'National Academic Performance and Progress System', 1),
('The "No Child Left Behind" policy in Nigerian education refers to:', 'edu', 'Free feeding in schools', 'Inclusive education for children with disabilities', 'UBE free and compulsory education policy', 'Free school uniforms', 2),
('Who is the current Registrar of JAMB as of 2024?', 'edu', 'Dibu Ojerinde', 'Ishaq Oloyede', 'Fabian Benjamin', 'Godswill Obioma', 1),
('JUPEB stands for:', 'edu', 'Joint Universities Preliminary Examination Board', 'Junior University Preparatory Examination Board', 'Joint University Pre-degree Examination Board', 'Junior Universities Pre-entry Examinations Body', 0),
('The National Mathematical Centre is located in:', 'edu', 'Lagos', 'Abuja', 'Sheda-Kwali, Abuja', 'Ibadan', 2),
('What does inclusive education mean?', 'edu', 'Education that includes science and arts', 'Education that accommodates all learners including those with special needs', 'Education free of charge for all', 'Education that includes vocational training', 1),
('The National Open University of Nigeria (NOUN) was re-established in:', 'edu', '1995', '2002', '2006', '2010', 1),
('The School of Basic Studies (SBS) is equivalent to which level of education?', 'edu', 'Primary school', 'Pre-degree / A-Level', 'Undergraduate', 'Postgraduate', 1),
('The SSCE is written by:', 'edu', 'JSS3 students', 'SS3 students', 'Primary 6 students', 'University students', 1),
('Which of the following is a private examination body operating in Nigeria?', 'edu', 'JAMB', 'NECO', 'Cambridge Assessment (IGCSE)', 'NERDC', 2),
('The Professional Diploma in Education (PDE) is awarded to:', 'edu', 'First degree holders who wish to become teachers', 'Secondary school graduates', 'Diploma holders in science', 'Postgraduate research students', 0),
('The ratio of pupils to teacher recommended by UNESCO at primary level is:', 'edu', '20:1', '30:1', '40:1', '50:1', 1),
('Which body funds school feeding programmes in Nigeria?', 'edu', 'UBEC', 'WAEC', 'NECO', 'O-MEAL through the Office of the VP', 3),
('The Almajiri Education Programme in Nigeria targeted:', 'edu', 'Girls in Northern Nigeria', 'Islamic pupils who roam streets begging', 'University drop-outs', 'Children of civil servants', 1),
('SUBEB stands for:', 'edu', 'State Universal Basic Education Board', 'State University Board of Education Budgets', 'Sub-regional Education Bureau', 'State Unified Basic Education Board', 0),
('The Nigerian education system currently operates a:', 'edu', '4-4-4-4 system', '6-3-3-4 system', '5-3-4-4 system', '8-4-4 system', 1),
('Which type of school is fully funded and managed by the Federal Government?', 'edu', 'Community schools', 'Unity schools (Federal Government Colleges)', 'Mission schools', 'Conventional schools', 1),
('The UNESCO Education for All (EFA) goals were set to be achieved by:', 'edu', '2010', '2015', '2020', '2030', 1),
('National Teachers Institute (NTI) is located in:', 'edu', 'Abuja', 'Lagos', 'Kaduna', 'Ibadan', 2),
('The minimum entry qualification for a PGDE is:', 'edu', 'OND', 'HND', 'First degree', 'NCE', 2),
('The mandate of NEMIS is:', 'edu', 'To conduct external examinations', 'To collect and manage education data and statistics', 'To fund tertiary education', 'To supervise private schools', 1),
('The distance between a pupil''s home and school recommended for the UBE is:', 'edu', '1 km', '2 km', '3 km', '5 km', 2),
('Which of the following is used to assess the affective domain in education?', 'edu', 'Written test', 'Observation checklist', 'Multiple choice test', 'Essay examination', 1),
('The Safe School Initiative (SSI) in Nigeria was launched in response to:', 'edu', 'Poor infrastructure', 'Boko Haram attacks on schools', 'Teacher shortage', 'Examination malpractice', 1),
('TVET stands for:', 'edu', 'Technical and Vocational Education and Training', 'Teacher Verification and Evaluation Tool', 'Tertiary Vocational Education Team', 'Technical Value Education Training', 0),
('Which country has the largest number of out-of-school children globally?', 'edu', 'India', 'Pakistan', 'Nigeria', 'Ethiopia', 2),
('The Bloom''s Taxonomy highest cognitive level is:', 'edu', 'Synthesis', 'Analysis', 'Create (Creating)', 'Evaluate', 2),
('The JAMB UTME minimum score required for most universities in Nigeria is:', 'edu', '150', '160', '180', '200', 1),
('The 2004 National Policy on Education revised the structure to:', 'edu', '9-3-4', '6-6-4', '6-3-3-4', '4-4-4-4', 2),
('The SDG goal for education (Goal 4) aims to ensure:', 'edu', 'Free tertiary education', 'Inclusive and equitable quality education for all', 'Mandatory vocational training', 'Equal number of male and female teachers', 1),
('The Teachers Registration Council of Nigeria (TRCN) was established by which Act?', 'edu', 'Education (National Minimum Standards) Act', 'Teachers Registration Council of Nigeria Act 1993', 'TRCN Act No. 31 of 1993', 'National Education Act 2004', 2),

-- ── ICT (50) ──
('What does "CPU" stand for in computing?', 'ict', 'Central Processing Unit', 'Computer Personal Unit', 'Central Program Utility', 'Core Processing Unit', 0),
('Which of the following is an example of an operating system?', 'ict', 'Microsoft Word', 'Google Chrome', 'Windows 11', 'Adobe Photoshop', 2),
('What does "WWW" stand for?', 'ict', 'World Wide Web', 'Wide World Web', 'World Web Wide', 'Web World Wide', 0),
('Which of the following is NOT a programming language?', 'ict', 'Python', 'Java', 'Linux', 'JavaScript', 2),
('What is the full meaning of "RAM" in computers?', 'ict', 'Random Access Memory', 'Read Access Memory', 'Rapid Application Memory', 'Remote Access Module', 0),
('Which device is used to connect a computer to the internet via a telephone line?', 'ict', 'Router', 'Hub', 'Modem', 'Switch', 2),
('What does "PDF" stand for?', 'ict', 'Portable Document Format', 'Printed Document File', 'Public Data Format', 'Personal Document Folder', 0),
('Which of the following is a search engine?', 'ict', 'Facebook', 'Twitter', 'Google', 'WhatsApp', 2),
('In Microsoft Excel, what symbol is used to begin a formula?', 'ict', '+', '#', '=', '@', 2),
('What is the storage capacity of 1 Gigabyte (GB)?', 'ict', '1,000 Kilobytes', '1,024 Megabytes', '512 Megabytes', '2,048 Kilobytes', 1),
('What does "HTML" stand for?', 'ict', 'HyperText Markup Language', 'High Technology Markup Language', 'HyperText Making Language', 'High Text Markup Logic', 0),
('Which of these is an input device?', 'ict', 'Monitor', 'Printer', 'Keyboard', 'Speaker', 2),
('What does "URL" stand for?', 'ict', 'Uniform Resource Locator', 'Universal Resource Link', 'Unique Reference Location', 'Uniform Reference Language', 0),
('The binary number system uses only:', 'ict', '0 and 1', '0, 1 and 2', '0 to 7', '0 to 9', 0),
('Which type of storage retains data even when the computer is turned off?', 'ict', 'RAM', 'Cache memory', 'ROM', 'Virtual memory', 2),
('What does "GUI" stand for?', 'ict', 'Graphical User Interface', 'General Utility Interface', 'Global Uniform Interface', 'Graphics Unified Integration', 0),
('Which of the following is a cloud storage service?', 'ict', 'USB flash drive', 'Google Drive', 'Hard disk', 'DVD', 1),
('The Internet of Things (IoT) refers to:', 'ict', 'Social media networks', 'Interconnected physical devices communicating over the internet', 'Online shopping platforms', 'Cloud computing services', 1),
('What is "phishing" in cybersecurity?', 'ict', 'Hacking a computer network', 'Tricking users into revealing sensitive information via fake communications', 'Installing antivirus software', 'A type of programming language', 1),
('Which company developed the Android operating system?', 'ict', 'Apple', 'Microsoft', 'Google', 'Samsung', 2),
('What does "LAN" stand for?', 'ict', 'Large Area Network', 'Local Area Network', 'Linked Access Node', 'Long-range Area Node', 1),
('Which programming language is primarily used for web development?', 'ict', 'C++', 'Java', 'HTML/CSS/JavaScript', 'Assembly', 2),
('The first computer virus is generally accepted to be:', 'ict', 'ILOVEYOU', 'Creeper', 'Melissa', 'WannaCry', 1),
('What does "SSD" stand for?', 'ict', 'Solid-State Drive', 'Super Storage Device', 'System Software Drive', 'Static Storage Disk', 0),
('A "firewall" in computing is used to:', 'ict', 'Cool down the CPU', 'Block unauthorised network access', 'Speed up the internet', 'Back up data', 1),
('Which of the following is NOT a web browser?', 'ict', 'Firefox', 'Safari', 'Linux', 'Opera', 2),
('What does "AI" stand for?', 'ict', 'Automated Internet', 'Artificial Intelligence', 'Advanced Integration', 'Automated Input', 1),
('The shortcut key for copying text in Windows is:', 'ict', 'Ctrl+V', 'Ctrl+X', 'Ctrl+C', 'Ctrl+Z', 2),
('What does "ISP" stand for?', 'ict', 'Internet Software Provider', 'International Service Protocol', 'Internet Service Provider', 'Integrated Software Platform', 2),
('Which of the following is an example of malware?', 'ict', 'Microsoft Word', 'Google Chrome', 'Ransomware', 'Zoom', 2),
('How many bits make one byte?', 'ict', '4', '8', '16', '32', 1),
('Which shortcut key is used to undo an action in Microsoft Word?', 'ict', 'Ctrl+Y', 'Ctrl+Z', 'Ctrl+U', 'Ctrl+A', 1),
('What is "Big Data"?', 'ict', 'A very large hard drive', 'Extremely large and complex data sets that require special tools to process', 'A database software', 'A government data portal', 1),
('Which of these is a programming concept used to repeat a block of code?', 'ict', 'Variable', 'Loop', 'Function', 'Array', 1),
('The domain extension ".gov.ng" is used by:', 'ict', 'Nigerian businesses', 'Nigerian government websites', 'Nigerian educational institutions', 'Nigerian NGOs', 1),
('What does "VPN" stand for?', 'ict', 'Virtual Private Network', 'Very Protected Node', 'Verified Public Network', 'Virtual Protocol Node', 0),
('Which technology is used for contactless payments?', 'ict', 'Bluetooth', 'WiFi', 'NFC (Near Field Communication)', '4G LTE', 2),
('In a spreadsheet, a cell reference like "B3" refers to:', 'ict', 'Row B, Column 3', 'Column B, Row 3', 'Sheet B, Cell 3', 'Block B3', 1),
('What does "HTTP" stand for?', 'ict', 'HyperText Transfer Protocol', 'High Technology Text Protocol', 'HyperText Technical Platform', 'Hyperlink Transfer Protocol', 0),
('Which of the following best describes "open source" software?', 'ict', 'Software that costs nothing', 'Software whose source code is publicly available for anyone to view or modify', 'Software made only for government use', 'Software that requires no installation', 1),
('What is the function of an "antivirus" software?', 'ict', 'Speed up the computer', 'Detect and remove malicious software', 'Connect to the internet', 'Manage files and folders', 1),
('Which of the following is an example of an output device?', 'ict', 'Keyboard', 'Mouse', 'Scanner', 'Projector', 3),
('The process of loading the operating system into a computer is called:', 'ict', 'Formatting', 'Booting', 'Compiling', 'Debugging', 1),
('Blockchain technology is primarily used in:', 'ict', 'Video streaming', 'Cryptocurrency transactions and secure record keeping', 'Social media', 'Email services', 1),
('What does "e-commerce" mean?', 'ict', 'Electronic computing', 'Buying and selling of goods and services over the internet', 'Email communication', 'Electronic government services', 1),
('Which of the following file extensions is associated with audio files?', 'ict', '.docx', '.mp3', '.xlsx', '.pdf', 1),
('The "cloud" in cloud computing refers to:', 'ict', 'Weather monitoring systems', 'Remote servers on the internet used to store and process data', 'A type of operating system', 'A wireless network protocol', 1),
('Machine Learning is a subset of:', 'ict', 'Robotics', 'Cybersecurity', 'Artificial Intelligence', 'Database Management', 2),
('The correct order of data sizes from smallest to largest is:', 'ict', 'Bit, Byte, Kilobyte, Megabyte, Gigabyte', 'Byte, Bit, Megabyte, Kilobyte, Gigabyte', 'Kilobyte, Byte, Bit, Megabyte, Gigabyte', 'Bit, Kilobyte, Byte, Megabyte, Gigabyte', 0),
('Nigeria''s National Information Technology Development Agency (NITDA) was established in:', 'ict', '1999', '2001', '2004', '2007', 1),

-- ── RELIGION (50) ──
('How many books are in the Old Testament of the Christian Bible?', 'religion', '27', '39', '66', '46', 1),
('The holy book of Islam is called:', 'religion', 'The Torah', 'The Bible', 'The Quran', 'The Vedas', 2),
('In Islam, how many times a day are Muslims required to pray (Salat)?', 'religion', '3', '4', '5', '7', 2),
('Which river is considered the most sacred in Hinduism?', 'religion', 'Nile', 'Amazon', 'Ganges', 'Yangtze', 2),
('The first book of the Bible is:', 'religion', 'Exodus', 'Genesis', 'Leviticus', 'Numbers', 1),
('In Christianity, the period of fasting and prayer before Easter is called:', 'religion', 'Advent', 'Pentecost', 'Lent', 'Epiphany', 2),
('What is the meaning of "Islam" in Arabic?', 'religion', 'Peace', 'Submission', 'Faith', 'Prayer', 1),
('The Hijab worn by Muslim women is primarily a symbol of:', 'religion', 'Cultural identity', 'Modesty and piety', 'Political allegiance', 'Social status', 1),
('According to the Bible, Jesus Christ was baptised in which river?', 'religion', 'Nile', 'Euphrates', 'Jordan', 'Tigris', 2),
('The five pillars of Islam include all of the following EXCEPT:', 'religion', 'Salat (Prayer)', 'Hajj (Pilgrimage)', 'Zakat (Almsgiving)', 'Jihad', 3),
('How many books are in the New Testament?', 'religion', '22', '27', '30', '39', 1),
('The Islamic calendar is based on:', 'religion', 'The solar calendar', 'The lunar calendar', 'The Gregorian calendar', 'The Julian calendar', 1),
('Ramadan is the _____ month of the Islamic calendar:', 'religion', '5th', '7th', '9th', '12th', 2),
('What is "Zakat" in Islam?', 'religion', 'Daily prayer', 'Obligatory almsgiving (charity)', 'Fasting during Ramadan', 'Pilgrimage to Mecca', 1),
('The city considered holiest in Islam is:', 'religion', 'Medina', 'Jerusalem', 'Mecca', 'Cairo', 2),
('In Christianity, the Holy Trinity consists of:', 'religion', 'God, Jesus, and Moses', 'Father, Son, and Holy Spirit', 'God, the Prophets, and the Angels', 'God, Mary, and Jesus', 1),
('The Torah is the holy scripture of:', 'religion', 'Christianity', 'Islam', 'Judaism', 'Hinduism', 2),
('In Islam, the pilgrimage to Mecca (Hajj) must be performed at least:', 'religion', 'Once in a lifetime if able', 'Every year', 'Every 5 years', 'Twice in a lifetime', 0),
('What does "Eid-ul-Fitr" celebrate?', 'religion', 'The birth of Prophet Muhammad', 'The end of Ramadan fasting', 'The journey to Mecca', 'The revelation of the Quran', 1),
('The Psalms are found in which part of the Bible?', 'religion', 'The New Testament', 'The Apocrypha', 'The Old Testament', 'The Epistles', 2),
('The Anglican Church in Nigeria is known as:', 'religion', 'Catholic Church of Nigeria', 'Church of Nigeria (Anglican Communion)', 'Redeemed Christian Church', 'Living Faith Church', 1),
('In Christianity, Pentecost Sunday celebrates:', 'religion', 'The resurrection of Jesus', 'The birth of Jesus', 'The descent of the Holy Spirit on the Apostles', 'The baptism of Jesus', 2),
('How many chapters (Surahs) are in the Quran?', 'religion', '99', '100', '114', '120', 2),
('Who is considered the founder of Buddhism?', 'religion', 'Confucius', 'Siddhartha Gautama', 'Laozi', 'Mahavira', 1),
('The Sabbath day in Judaism is observed on:', 'religion', 'Sunday', 'Friday', 'Saturday', 'Thursday', 2),
('What is the name of the Muslim call to prayer?', 'religion', 'Khutbah', 'Adhan', 'Salah', 'Tasbih', 1),
('In the Bible, which book immediately follows Genesis?', 'religion', 'Leviticus', 'Numbers', 'Deuteronomy', 'Exodus', 3),
('The CAN (Christian Association of Nigeria) was founded in:', 'religion', '1960', '1976', '1984', '1990', 1),
('What does "Eid-ul-Adha" commemorate?', 'religion', 'Abraham''s willingness to sacrifice his son', 'The end of Ramadan', 'The birth of Prophet Muhammad', 'The night of power', 0),
('The Jumu''ah in Islam refers to:', 'religion', 'Friday congregational prayer', 'The pilgrimage to Mecca', 'Monthly charity payment', 'Nightly prayer during Ramadan', 0),
('Which Nigerian governor introduced Sharia law in Zamfara State in 1999?', 'religion', 'Attahiru Bafarawa', 'Ahmad Sani Yerima', 'Abdullahi Ganduje', 'Bello Matawalle', 1),
('In Yoruba traditional religion, the supreme deity is called:', 'religion', 'Sango', 'Ogun', 'Olodumare', 'Obatala', 2),
('The CRK subject in Nigerian schools stands for:', 'religion', 'Christian Religion and Knowledge', 'Christian Religious Knowledge', 'Christ Revealed Knowledge', 'Christian Revelation and Knowledge', 1),
('In Igbo traditional religion, the creator God is called:', 'religion', 'Amadioha', 'Ala', 'Chukwu', 'Ikenga', 2),
('The Rosary is associated with which denomination of Christianity?', 'religion', 'Protestantism', 'Catholicism', 'Pentecostalism', 'Anglicanism', 1),
('In Islam, "Tawhid" means:', 'religion', 'Pilgrimage', 'Prayer', 'The oneness of God', 'Fasting', 2),
('Which prophet is shared and honoured by Christianity, Islam, and Judaism?', 'religion', 'Moses', 'Elijah', 'John', 'Paul', 0),
('The Islamic Studies subject in Nigerian schools is also known as:', 'religion', 'IRS', 'ISS', 'IRK (Islamic Religious Knowledge)', 'IRS (Islamic Religion Studies)', 2),
('The "Sermon on the Mount" was delivered by:', 'religion', 'Moses', 'Paul', 'Jesus Christ', 'Peter', 2),
('What is "Taqwa" in Islam?', 'religion', 'Prayer beads', 'Mindfulness and fear of God / piety', 'The Quran recitation', 'The pilgrimage', 1),
('The Hausa traditional religion''s high god is called:', 'religion', 'Magiro', 'Bori', 'Ubangiji', 'Sarkin Ruwa', 2),
('What does "RCCG" stand for?', 'religion', 'Redeemed Christian Church of God', 'Reformed Christian Community of God', 'Regenerated Christian Church of God', 'Renewed Christ Church of God', 0),
('In Islam, the direction Muslims face during prayer toward Mecca is called:', 'religion', 'Qiblah', 'Masjid', 'Minaret', 'Mihrab', 0),
('The Ecumenical movement aims to:', 'religion', 'Promote Islam globally', 'Unite all Christian denominations', 'Eliminate traditional religions', 'Promote interfaith conflict', 1),
('Which Nigerian state has a significant Christian and Muslim population and is known for religious tension?', 'religion', 'Kwara', 'Kaduna', 'Imo', 'Oyo', 1),
('In Judaism, the weekly Sabbath begins at:', 'religion', 'Friday morning', 'Friday sunset', 'Saturday morning', 'Saturday sunset', 1),
('Who wrote most of the Epistles in the New Testament?', 'religion', 'Peter', 'John', 'Paul', 'James', 2),
('The Confucian philosophy originated in:', 'religion', 'Japan', 'India', 'China', 'Korea', 2),
('In the Nigerian context, "Ifa" divination is associated with:', 'religion', 'Hausa/Fulani culture', 'Igbo culture', 'Yoruba culture', 'Tiv culture', 2),
('The word "gospel" literally means:', 'religion', 'Holy word', 'Good news', 'Sacred teaching', 'The commandments', 1),

-- ── COMMON ENTRANCE (50) ──
('What is the capital city of Nigeria?', 'entrance', 'Lagos', 'Kano', 'Abuja', 'Ibadan', 2),
('Which river is the longest in Nigeria?', 'entrance', 'Benue River', 'Niger River', 'Kaduna River', 'Cross River', 1),
('What is 15% of 200?', 'entrance', '20', '25', '30', '35', 2),
('Which of the following is a mammal?', 'entrance', 'Crocodile', 'Eagle', 'Whale', 'Tilapia', 2),
('How many sides does a hexagon have?', 'entrance', '5', '6', '7', '8', 1),
('What is the plural of "child"?', 'entrance', 'Childs', 'Childrens', 'Children', 'Child', 2),
('The process by which plants make their own food using sunlight is called:', 'entrance', 'Respiration', 'Photosynthesis', 'Digestion', 'Transpiration', 1),
('Which planet is closest to the Sun?', 'entrance', 'Venus', 'Earth', 'Mars', 'Mercury', 3),
('What is the sum of angles in a triangle?', 'entrance', '90 degrees', '120 degrees', '180 degrees', '360 degrees', 2),
('Who wrote the Nigerian national anthem "Arise O Compatriots"?', 'entrance', 'Wole Soyinka', 'A committee of Nigerians', 'Chinua Achebe', 'John Okafor', 1),
('How many states are in Nigeria?', 'entrance', '30', '34', '36', '38', 2),
('What is the largest ocean in the world?', 'entrance', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean', 3),
('Which of these is NOT a primary colour?', 'entrance', 'Red', 'Blue', 'Green', 'Yellow', 3),
('What gas do plants absorb from the atmosphere during photosynthesis?', 'entrance', 'Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen', 2),
('Nigeria gained independence in:', 'entrance', '1957', '1960', '1963', '1966', 1),
('The simple past tense of "go" is:', 'entrance', 'Goed', 'Gone', 'Went', 'Goes', 2),
('What is 144 divided by 12?', 'entrance', '10', '11', '12', '13', 2),
('Which organ pumps blood around the body?', 'entrance', 'Liver', 'Lungs', 'Kidney', 'Heart', 3),
('The adjective form of "beauty" is:', 'entrance', 'Beautify', 'Beautiful', 'Beautifully', 'Beauteous', 1),
('Which continent is Nigeria located in?', 'entrance', 'Asia', 'Europe', 'Africa', 'South America', 2),
('What is the boiling point of water at sea level?', 'entrance', '90 degrees C', '95 degrees C', '100 degrees C', '110 degrees C', 2),
('Which of these is a conjunction?', 'entrance', 'Quickly', 'Beautiful', 'Because', 'Table', 2),
('How many minutes are in 3 hours?', 'entrance', '150', '160', '180', '200', 2),
('The national currency of Nigeria is the:', 'entrance', 'Dollar', 'Pound', 'Naira', 'Cedi', 2),
('Which of the following is a reptile?', 'entrance', 'Frog', 'Bat', 'Tortoise', 'Salmon', 2),
('What does H2O represent?', 'entrance', 'Hydrogen peroxide', 'Salt water', 'Water', 'Carbon dioxide', 2),
('Which of these numbers is a prime number?', 'entrance', '9', '15', '17', '21', 2),
('The antonym of "ancient" is:', 'entrance', 'Old', 'Modern', 'Broken', 'Small', 1),
('What is the capital of Ogun State?', 'entrance', 'Sagamu', 'Ijebu-Ode', 'Abeokuta', 'Ilaro', 2),
('Which part of a plant absorbs water and minerals from the soil?', 'entrance', 'Leaves', 'Stem', 'Root', 'Flower', 2),
('What is 23 multiplied by 4?', 'entrance', '82', '88', '92', '96', 2),
('Which of these is a vowel?', 'entrance', 'B', 'T', 'E', 'K', 2),
('The River Niger enters Nigeria from which country?', 'entrance', 'Cameroon', 'Benin Republic', 'Guinea', 'Mali', 1),
('A baby dog is called a:', 'entrance', 'Calf', 'Kid', 'Cub', 'Puppy', 3),
('Which of the following is NOT a sense organ?', 'entrance', 'Eye', 'Ear', 'Nose', 'Stomach', 3),
('The correct spelling is:', 'entrance', 'Recieve', 'Receive', 'Recive', 'Receieve', 1),
('How many grams are in 1 kilogram?', 'entrance', '100', '500', '1000', '10000', 2),
('Who was Nigeria''s first Head of State?', 'entrance', 'Yakubu Gowon', 'Nnamdi Azikiwe', 'Aguiyi-Ironsi', 'Obafemi Awolowo', 2),
('What does LCM stand for in Mathematics?', 'entrance', 'Longest Common Multiple', 'Least Common Multiple', 'Largest Common Multiple', 'Lowest Common Mean', 1),
('Which city is known as the commercial capital of Nigeria?', 'entrance', 'Abuja', 'Port Harcourt', 'Kano', 'Lagos', 3),
('A triangle with all three sides equal is called:', 'entrance', 'Scalene', 'Isosceles', 'Equilateral', 'Right-angled', 2),
('The synonym of "courageous" is:', 'entrance', 'Afraid', 'Brave', 'Quiet', 'Weak', 1),
('How many seconds are in one minute?', 'entrance', '30', '60', '90', '100', 1),
('Which of these is a natural disaster?', 'entrance', 'Building collapse', 'Flood', 'Road accident', 'Fire outbreak', 1),
('The plural of "tooth" is:', 'entrance', 'Tooths', 'Teeths', 'Teeth', 'Toothes', 2),
('What is the square root of 81?', 'entrance', '7', '8', '9', '10', 2),
('Which Nigerian president introduced the "War Against Indiscipline" (WAI)?', 'entrance', 'Olusegun Obasanjo', 'Ibrahim Babangida', 'Muhammadu Buhari', 'Ernest Shonekan', 2),
('The word "the" is an example of which part of speech?', 'entrance', 'Pronoun', 'Adjective', 'Article', 'Preposition', 2),
('What is the area of a rectangle with length 8cm and width 5cm?', 'entrance', '26 cm squared', '30 cm squared', '40 cm squared', '13 cm squared', 2),
('Which of these animals is nocturnal (active at night)?', 'entrance', 'Eagle', 'Butterfly', 'Owl', 'Lizard', 2)

ON CONFLICT DO NOTHING;

